-- Seed data — intentionally empty.
--
-- Runs automatically on `supabase db reset`. The starter ships with no tables,
-- so there is nothing to seed yet. Add inserts here once you create your tables.
--
-- EXAMPLE (matches the commented table in the baseline migration):
--
-- insert into public.example_items (title, body)
-- values ('Welcome', 'Replace this content from the admin panel.')
-- on conflict do nothing;
