-- Baseline schema — intentionally empty.
--
-- The starter ships with NO domain tables so you start from a clean DB.
-- Below is a commented EXAMPLE of the conventions every table should follow:
--   * uuid primary key + created_at / updated_at timestamps
--   * `trg_set_updated_at` trigger (uses public.set_updated_at() from the helpers migration)
--   * RLS enabled with `public_read` (anon select) + `auth_all` (authenticated full access)
--   * `sort_order` column if the resource is reorderable via reorder_by_sort_order()
--
-- Create real tables with their own migration: `pnpm db:migration <name>`,
-- then `pnpm db:push` (or `pnpm db:reset`) and `pnpm db:types`.

-- ============================================================
-- EXAMPLE — copy this block into a new migration and rename.
-- ============================================================
-- create table public.example_items (
--   id          uuid primary key default gen_random_uuid(),
--   title       text not null,
--   body        text,
--   is_active   boolean default true,
--   sort_order  int default 0,
--   created_at  timestamptz default now(),
--   updated_at  timestamptz default now()
-- );
--
-- create trigger trg_set_updated_at before update on public.example_items
--   for each row execute function public.set_updated_at();
--
-- alter table public.example_items enable row level security;
--
-- create policy "public_read" on public.example_items
--   for select using (true);
--
-- create policy "auth_all" on public.example_items
--   for all to authenticated using (true) with check (true);
